### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by simple1213** [Dtrycode/ToupleGDD#1]
I would like to ask the author why the model codes of S2V-DDQN, S2V-DuelDQN and S2V-DuelDDQN are missing for comparison？

**Comment by Dtrycode** [comment]
Thanks a lot for your interest!
The codes of "S2V_DQN" and "S2V_DUEL" can be viewed at line 21 and line 495 respectively in the file "models.py".
To enable or disable "Double" setting, please set "args.double_dqn" (at line 60 in the file "main.py") to "True" or "False" respectively.
The "Double" setting is processed at lines 45-79 in the file "rl_agents.py" for different models.
